# Generated by Django 5.2.7 on 2025-10-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RfidScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=10)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
    ]
