# Generated by Django 5.2.7 on 2025-10-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSSDairy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfidscan',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rfidscan',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
