# Generated by Django 5.2.7 on 2025-10-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSSDairy', '0002_alter_rfidscan_date_alter_rfidscan_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidscan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rfidscan',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rfidscan',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='rfidscan',
            name='uid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
